### ISSUE TITLE
PropertiesReader is insufficient and limits the server structure

### ISSUE THREAD

**Issue by ehenoma** [CuukyOfficial/CFW#7]
The [Server Properties Reader](https://github.com/CuukyOfficial/CFW/blob/master/CFW%20-%20Cuuky%20FrameWork/src/de/cuuky/cfw/utils/ServerPropertiesReader.java) only parses a subset of the [properties file syntax](https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html), comments and multi-line values are not supported.

Furthermore it forces the Location to be `/server.properties` (relative to the server path). 
This limitation prevents me from using the [Varo Plugin](https://github.com/CuukyOfficial/VaroPlugin) (which depends on this class).
I am using a custom config path `--config` and can not change my server structure to comply with the `ServerPropertiesReader`.

Plugins that read files like server.properties or logs should not hardcore the paths.

AFAIK: The Minecraft Server class has a method to access a properties object that can be used when
NMS is not off limits.

If this will be addressed, the dependency version within the Varo Plugin should be updated aswell.

**Comment by CuukyOfficial** [comment]
[This has been fixed](https://github.com/CuukyOfficial/CFW/commit/00466923a8b065f0df240da569af8db350f9b8e0).
Thank you for your help.
